"""Deterministic VapourSynth reference scripts for headless operation."""

from __future__ import annotations

import hashlib
import json
from dataclasses import asdict, dataclass
from enum import StrEnum
from pathlib import Path
from typing import Any


class TemporalFilter(StrEnum):
    PROGRESSIVE = "progressive"
    IVTC_TFF = "ivtc_tff"
    IVTC_BFF = "ivtc_bff"
    BWDIF_TFF = "bwdif_tff"
    BWDIF_BFF = "bwdif_bff"
    HYBRID_SAFE_BOB_TFF = "hybrid_safe_bob_tff"
    HYBRID_SAFE_BOB_BFF = "hybrid_safe_bob_bff"


@dataclass(frozen=True, slots=True)
class Crop:
    left: int = 0
    top: int = 0
    right: int = 0
    bottom: int = 0

    def __post_init__(self) -> None:
        if any(value < 0 or value % 2 for value in asdict(self).values()):
            raise ValueError("4:2:0 crop values must be non-negative even integers")

    @property
    def enabled(self) -> bool:
        return any(asdict(self).values())


@dataclass(frozen=True, slots=True)
class ReferenceScriptPlan:
    source: Path
    cache_path: Path
    script_path: Path
    track: int = 0
    temporal_filter: TemporalFilter = TemporalFilter.PROGRESSIVE
    crop: Crop = Crop()
    output_width: int | None = None
    output_height: int | None = None
    decoder_threads: int = 0

    def __post_init__(self) -> None:
        if self.track < 0:
            raise ValueError("video track cannot be negative")
        if (self.output_width is None) != (self.output_height is None):
            raise ValueError("output width and height must be supplied together")
        if self.output_width is not None and (
            self.output_width < 16
            or self.output_height is None
            or self.output_height < 16
            or self.output_width % 2
            or self.output_height % 2
        ):
            raise ValueError("output dimensions must be even and at least 16")


def render_reference_script(plan: ReferenceScriptPlan) -> str:
    source = json.dumps(str(plan.source.resolve(strict=False)))
    cache = json.dumps(str(plan.cache_path.resolve(strict=False)))
    lines = [
        "# Generated by BDEncode. Edits make the recorded hash invalid.",
        "from vapoursynth import core",
        "",
        "src = core.bs.VideoSource(",
        f"    source={source}, track={plan.track}, threads={plan.decoder_threads},",
        f"    cachemode=4, cachepath={cache}, maxdecoders=1, showprogress=True,",
        # Downstream Y4M consumers and encoders require one stable format.  A
        # Blu-ray title is constant-format; fail rather than silently accepting
        # a malformed source whose format changes mid-playlist.
        # The encode is CFR and its full output timeline is checked against
        # vspipe --info. BestSource's exporttimestamps=True changes the return
        # value into a multi-key VSMap and materializes an otherwise unused
        # array for every frame.
        "    variableformat=0,",
        ")",
    ]
    temporal = plan.temporal_filter
    if temporal is TemporalFilter.IVTC_TFF:
        lines.extend(
            ["src = core.vivtc.VFM(src, order=1)", "src = core.vivtc.VDecimate(src)"]
        )
    elif temporal is TemporalFilter.IVTC_BFF:
        lines.extend(
            ["src = core.vivtc.VFM(src, order=0)", "src = core.vivtc.VDecimate(src)"]
        )
    elif temporal is TemporalFilter.BWDIF_TFF:
        lines.append("src = core.bwdif.Bwdif(src, field=1)")
    elif temporal is TemporalFilter.BWDIF_BFF:
        lines.append("src = core.bwdif.Bwdif(src, field=0)")
    elif temporal is TemporalFilter.HYBRID_SAFE_BOB_TFF:
        lines.append("src = core.bwdif.Bwdif(src, field=3)")
    elif temporal is TemporalFilter.HYBRID_SAFE_BOB_BFF:
        lines.append("src = core.bwdif.Bwdif(src, field=2)")

    if plan.crop.enabled:
        lines.append(
            "src = core.std.CropRel(src, "
            f"left={plan.crop.left}, top={plan.crop.top}, "
            f"right={plan.crop.right}, bottom={plan.crop.bottom})"
        )
    if plan.output_width is not None and plan.output_height is not None:
        lines.append(
            f"src = core.resize.Spline36(src, width={plan.output_width}, height={plan.output_height})"
        )
    lines.extend(["", "src.set_output()", ""])
    return "\n".join(lines)


def script_record(plan: ReferenceScriptPlan, content: str) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "source": str(plan.source),
        "cache_path": str(plan.cache_path),
        "track": plan.track,
        "temporal_filter": plan.temporal_filter.value,
        "crop": asdict(plan.crop),
        "output_width": plan.output_width,
        "output_height": plan.output_height,
        "decoder_threads": plan.decoder_threads,
        "script_sha256": hashlib.sha256(content.encode("utf-8")).hexdigest(),
    }
